// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Start(rateHz: number, batchIntervalMS: number): $CancellablePromise<$models.ActivityProbeControlResult> {
    return $Call.ByID(1518847004, rateHz, batchIntervalMS);
}

export function Status(): $CancellablePromise<$models.ActivityProbeStatus> {
    return $Call.ByID(1845099586);
}

export function Stop(): $CancellablePromise<$models.ActivityProbeStatus> {
    return $Call.ByID(996233912);
}
