// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelInsertion(insertionID: string): $CancellablePromise<$models.InsertionControlResult> {
    return $Call.ByID(3347621966, insertionID);
}

export function EnqueueInsertion(callID: string, text: string): $CancellablePromise<$models.InsertionControlResult> {
    return $Call.ByID(2241189700, callID, text);
}
