// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Start(rateHz: number, batchIntervalMS: number): $CancellablePromise<$models.EventControlResult> {
    return $Call.ByID(702218467, rateHz, batchIntervalMS);
}

export function Status(): $CancellablePromise<$models.EventSourceStatus> {
    return $Call.ByID(3860642227);
}

export function Stop(): $CancellablePromise<$models.EventSourceStatus> {
    return $Call.ByID(389018865);
}
