// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopruntime$0 from "../../internal/desktopruntime/models.js";

export interface APIError {
    "code": string;
    "message": string;
}

export interface EventControlResult {
    "status": EventSourceStatus;
    "error"?: APIError | null;
}

export interface EventSourceStatus {
    "running": boolean;
    "rateHz": number;
    "produced": number;
    "delivered": number;
    "dropped": number;
    "queueDropped": number;
    "transportDropped": number;
    "queueDepth": number;
    "queueCapacity": number;
}

export interface Preferences {
    "batchIntervalMs": number;
    "windowWidth": number;
    "windowHeight": number;
}

export interface PreferencesResult {
    "preferences": Preferences;
    "error"?: APIError | null;
}

export interface RuntimeActionResult {
    "action": string;
    "completed": boolean;
    "error"?: APIError | null;
}

export interface RuntimeStatusResult {
    "runtimeRoot": string;
    "status": desktopruntime$0.ServiceStatus;
    "error"?: APIError | null;
}

export interface SavePreferencesResult {
    "saved": boolean;
    "error"?: APIError | null;
}
