// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopapi$0 from "../../internal/desktopapi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as execution$0 from "../../internal/execution/models.js";

export interface ActivityProbeControlResult {
    "status": ActivityProbeStatus;
    "error"?: desktopapi$0.APIError | null;
}

export interface ActivityProbeStatus {
    "running": boolean;
    "rateHz": number;
    "epoch": string;
    "latestSequence": string;
    "publishedTotal": string;
    "deliveredTotal": string;
    "droppedTotal": string;
    "sourceDroppedTotal": string;
    "transportDroppedTotal": string;
    "queueDepth": number;
    "queueCapacity": number;
}

export interface InsertionControlResult {
    "insertion": execution$0.Insertion;
    "ack": boolean;
    "error"?: desktopapi$0.APIError | null;
}

export interface Preferences {
    "batchIntervalMs": number;
    "windowWidth": number;
    "windowHeight": number;
}

export interface PreferencesResult {
    "preferences": Preferences;
    "error"?: desktopapi$0.APIError | null;
}

export interface SavePreferencesResult {
    "saved": boolean;
    "error"?: desktopapi$0.APIError | null;
}
