// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Insertion {
    "insertion_id": string;
    "target_call_id": string;
    "status": InsertionStatus;
    "text_preview"?: string;
    "text_bytes": number;
    "created_at": string;
    "updated_at": string;
    "expires_at": string;
    "delivered_at"?: string | null;
    "reason"?: string;
}

export enum InsertionStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    InsertionAccepted = "accepted",
    InsertionDelivered = "delivered",
    InsertionRejected = "rejected",
    InsertionExpired = "expired",
    InsertionCancelled = "cancelled",
};
