// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Snapshot {
    "observedAt": string;
    "availability": string;
    "state": string;
    "stale": boolean;
    "browserEnabled": boolean;
    "acpEnabled": boolean;
    "companyRequiredEdgePolicies": number;
    "owners": number;
    "leases": number;
    "activeLeases": number;
    "expiredLeases": number;
    "releasingLeases": number;
    "failedLeases": number;
    "unownedLeases": number;
    "workers": number;
    "readyWorkers": number;
    "failedWorkers": number;
    "activeOperations": number;
    "queuedOperations": number;
    "maxConcurrency": number;
    "queueCapacity": number;
    "managedOrphans": number;
    "externalOrphans": number;
    "lifecycleError": boolean;
}
