// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopruntime$0 from "../desktopruntime/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckProfileUpdate(profileID: string): $CancellablePromise<$models.ACPProfileProbeResult> {
    return $Call.ByID(3524749791, profileID);
}

export function Close(profileID: string, sessionID: string): $CancellablePromise<$models.ACPMutationResult> {
    return $Call.ByID(2847673345, profileID, sessionID);
}

export function ProbeProfile(profileID: string): $CancellablePromise<$models.ACPProfileProbeResult> {
    return $Call.ByID(1534005872, profileID);
}

/**
 * Profiles use the existing simplified configuration DTO (id, displayName,
 * kind, command, args, enabled). An empty new ID is assigned by the backend.
 */
export function SaveSettings(expectedRevision: string, enabled: boolean, defaultProfile: string, profiles: desktopruntime$0.ACPProfileSettings[] | null): $CancellablePromise<$models.ACPSettingsMutationResult> {
    return $Call.ByID(949748259, expectedRevision, enabled, defaultProfile, profiles);
}

/**
 * Settings reads configuration only; it never probes Core, Memory or adapters.
 */
export function Settings(): $CancellablePromise<$models.ACPManagerSnapshot> {
    return $Call.ByID(2707635558);
}

export function Status(): $CancellablePromise<$models.ACPStatusResult> {
    return $Call.ByID(2429849165);
}

export function UpdateLifecycle(update: $models.ACPLifecycleUpdate): $CancellablePromise<$models.ACPMutationResult> {
    return $Call.ByID(107031406, update);
}

export function UpdateProfileAdapter(profileID: string, expectedPlan: string): $CancellablePromise<$models.ACPProfileUpdateMutationResult> {
    return $Call.ByID(3803654350, profileID, expectedPlan);
}
