// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Close(profileID: string, sessionID: string): $CancellablePromise<$models.ACPMutationResult> {
    return $Call.ByID(2847673345, profileID, sessionID);
}

export function Status(): $CancellablePromise<$models.ACPStatusResult> {
    return $Call.ByID(2429849165);
}

export function UpdateLifecycle(update: $models.ACPLifecycleUpdate): $CancellablePromise<$models.ACPMutationResult> {
    return $Call.ByID(107031406, update);
}
