// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Read(): $CancellablePromise<$models.BasicSettingsResult> {
    return $Call.ByID(2079393400);
}

export function Save(settings: $models.BasicSettings): $CancellablePromise<$models.BasicSettingsSaveResult> {
    return $Call.ByID(3458881057, settings);
}
