// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Action(action: string): $CancellablePromise<$models.ConnectionActionResult> {
    return $Call.ByID(2613481889, action);
}

export function Status(): $CancellablePromise<$models.ConnectionStatusResult> {
    return $Call.ByID(2883329957);
}
