// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Manifest(): $CancellablePromise<$models.Manifest> {
    return $Call.ByID(1015710376);
}

export function Negotiate(request: $models.NegotiationRequest): $CancellablePromise<$models.NegotiationResult> {
    return $Call.ByID(4102056607, request);
}
