// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AuthorizationStatus(name: string): $CancellablePromise<$models.MCPAuthorizationStatusResult> {
    return $Call.ByID(2862500754, name);
}

export function Authorize(name: string, callbackID: string, expectedRevision: string, expectedGeneration: string): $CancellablePromise<$models.MCPAuthorizationResult> {
    return $Call.ByID(218423642, name, callbackID, expectedRevision, expectedGeneration);
}

export function ClearAuthorization(name: string, expectedRevision: string, expectedGeneration: string): $CancellablePromise<$models.MCPActionResult> {
    return $Call.ByID(3403326913, name, expectedRevision, expectedGeneration);
}

export function Create(expectedRevision: string, input: $models.MCPConfigInput): $CancellablePromise<$models.MCPMutationResult> {
    return $Call.ByID(4293104111, expectedRevision, input);
}

export function Environment(name: string, expectedRevision: string, expectedGeneration: string): $CancellablePromise<$models.MCPEnvironmentResult> {
    return $Call.ByID(2486539776, name, expectedRevision, expectedGeneration);
}

export function Inspect(name: string): $CancellablePromise<$models.MCPServerResult> {
    return $Call.ByID(2307741105, name);
}

export function PurgeEnvironment(name: string, expectedRevision: string, expectedGeneration: string, expectedEnvRevision: string): $CancellablePromise<$models.MCPEnvironmentResult> {
    return $Call.ByID(134977999, name, expectedRevision, expectedGeneration, expectedEnvRevision);
}

export function Reconnect(name: string, expectedRevision: string, expectedGeneration: string): $CancellablePromise<$models.MCPReconnectResult> {
    return $Call.ByID(1224557772, name, expectedRevision, expectedGeneration);
}

export function Remove(name: string, expectedRevision: string, expectedGeneration: string): $CancellablePromise<$models.MCPMutationResult> {
    return $Call.ByID(2455885323, name, expectedRevision, expectedGeneration);
}

export function SetEnabled(name: string, enabled: boolean, expectedRevision: string, expectedGeneration: string): $CancellablePromise<$models.MCPMutationResult> {
    return $Call.ByID(1608132134, name, enabled, expectedRevision, expectedGeneration);
}

export function SetEnvironment(name: string, key: string, value: string, expectedRevision: string, expectedGeneration: string, expectedEnvRevision: string): $CancellablePromise<$models.MCPEnvironmentResult> {
    return $Call.ByID(2073178530, name, key, value, expectedRevision, expectedGeneration, expectedEnvRevision);
}

export function Snapshot(): $CancellablePromise<$models.MCPSnapshotResult> {
    return $Call.ByID(3527668959);
}

export function UnsetEnvironment(name: string, key: string, expectedRevision: string, expectedGeneration: string, expectedEnvRevision: string): $CancellablePromise<$models.MCPEnvironmentResult> {
    return $Call.ByID(3308846601, name, key, expectedRevision, expectedGeneration, expectedEnvRevision);
}

export function Update(name: string, expectedRevision: string, expectedGeneration: string, input: $models.MCPConfigInput): $CancellablePromise<$models.MCPMutationResult> {
    return $Call.ByID(1813817558, name, expectedRevision, expectedGeneration, input);
}
