// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface APIError {
    "code": string;
    "message": string;
    "category": ErrorCategory;
    "retryable": boolean;
    "details"?: { [_ in string]?: string } | null;
}

export enum AccessLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AccessRead = "read",
    AccessMutating = "mutating",
    AccessPrivileged = "privileged",
};

export enum Availability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AvailabilityAvailable = "available",
    AvailabilityExperimental = "experimental",
    AvailabilityUnavailable = "unavailable",
};

export enum Domain {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DomainRuntime = "runtime",
    DomainConnection = "connection",
    DomainACP = "acp",
    DomainBrowser = "browser",
    DomainActivity = "activity",
    DomainPermission = "permission",
    DomainMCP = "mcp",
    DomainPlugin = "plugin",
    DomainUpdate = "update",
    DomainDiagnostics = "diagnostics",
};

export interface DomainCapability {
    "domain": Domain;
    "version": number;
    "availability": Availability;
    "operations": OperationCapability[] | null;
    "streams": StreamCapability[] | null;
    "reason"?: string;
}

export enum ErrorCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorCategoryValidation = "validation",
    ErrorCategoryUnavailable = "unavailable",
    ErrorCategoryOperation = "operation",
    ErrorCategoryTimeout = "timeout",
    ErrorCategoryCompatibility = "compatibility",
    ErrorCategoryInternal = "internal",
};

export interface Manifest {
    "protocolVersion": number;
    "minClientVersion": number;
    "maxClientVersion": number;
    "capabilities": DomainCapability[] | null;
}

export interface NegotiationRequest {
    "clientVersion": number;
    "domains"?: Domain[] | null;
}

export interface NegotiationResult {
    "accepted": boolean;
    "serverVersion": number;
    "capabilities": DomainCapability[] | null;
    "error"?: APIError | null;
}

export interface OperationCapability {
    "name": string;
    "access": AccessLevel;
    "requiresConfirmation": boolean;
}

export enum RuntimeAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeActionStart = "start",
    RuntimeActionStop = "stop",
    RuntimeActionRestart = "restart",
};

export interface RuntimeActionResult {
    "action": RuntimeAction;
    "completed": boolean;
    "error"?: APIError | null;
}

export interface RuntimeStatus {
    "running": boolean;
    "healthy": boolean;
    "startupEnabled": boolean;
    "nexusConnected": boolean;
}

export interface RuntimeStatusResult {
    "runtimeRoot": string;
    "status": RuntimeStatus;
    "error"?: APIError | null;
}

export interface StreamCapability {
    "name": string;
    "version": number;
    "transport": string;
    "backpressure": string;
    "maxPayloadBytes"?: number;
}
