// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as desktopruntime$0 from "../desktopruntime/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";

export interface ACPBrokerResources {
    "sessionId": string;
    "browser": ACPBrowserResources;
    "computer": ACPComputerResources;
}

export interface ACPBrowserResources {
    "leaseIds": string[] | null;
    "activeLeases": number;
    "cleanupIssues": number;
}

export interface ACPComputerResources {
    "sessionIds": string[] | null;
    "observeSessions": number;
    "actSessions": number;
}

export interface ACPLifecycleCounts {
    "managed": number;
    "loaded": number;
    "running": number;
    "ready": number;
    "idleManagedIdle": number;
    "idleManagedEligible": number;
    "closed": number;
    "autoCloseFailures": number;
}

export interface ACPLifecycleUpdate {
    "profileId": string;
    "sessionId": string;
    "policy": string;
    "idleCloseAfterMs"?: number;
}

/**
 * Command/args are explicit local Desktop configuration fields. Environment
 * mappings and raw persistence documents never cross this API boundary.
 */
export interface ACPManagedProfile {
    "id": string;
    "displayName"?: string;
    "runtimeKind": string;
    "preset": string;
    "source": string;
    "enabled": boolean;
    "configuredCommand"?: string;
    "configuredArgs": string[] | null;
    "protectedArgs"?: boolean;
    "detectedCommand"?: string;
    "detectedArgs"?: string[] | null;
    "availability": string;
    "installedVersion"?: string;
    "latestVersion"?: string;
    "updatePlan"?: string;
    "versionState": string;
    "canDetect": boolean;
    "canUpdate": boolean;
    "blockedReason"?: string;
}

export interface ACPManagerSnapshot {
    "revision": string;
    "enabled": boolean;
    "defaultProfile": string;
    "profiles": ACPManagedProfile[] | null;
    "capabilities": OperationCapability[] | null;
    "error"?: APIError | null;
}

export interface ACPMemoryStatus {
    "endpoint": string;
    "healthy": boolean;
    "version"?: string;
    "backend"?: string;
    "storagePath"?: string;
    "provider"?: string;
    "totalMemories"?: number;
    "protocolVersion": string;
    "error"?: APIError | null;
}

export interface ACPMutationResult {
    "completed": boolean;
    "error"?: APIError | null;
}

export interface ACPProcessStatus {
    "rootPid": number;
    "alive": boolean | null;
    "state": string;
    "descendantCount": number | null;
    "rssBytes": number | null;
    "treeRssBytes": number | null;
    "observedAt": string;
    "error"?: string;
}

export interface ACPProfileInfo {
    "id": string;
    "displayName"?: string;
    "kind": string;
    "source": string;
    "command"?: string;
    "enabled": boolean;
    "installed"?: boolean | null;
    "packageName"?: string;
    "latestVersion"?: string;
    "versionState": string;
}

export interface ACPProfileProbeResult {
    "profile"?: ACPManagedProfile | null;
    "error"?: APIError | null;
}

export interface ACPProfileStatus {
    "profile": ACPProfileInfo;
    "observedAt"?: string;
    "counts": ACPLifecycleCounts;
    "sessions": ACPSessionLifecycle[] | null;
    "adapterProcess"?: ACPProcessStatus | null;
    "resources": ACPBrokerResources[] | null;
    "error"?: APIError | null;
}

export interface ACPProfileUpdateMutationResult {
    "completed": boolean;
    "restartRequired": boolean;
    "runtimeImpact": string;
    "profile"?: ACPManagedProfile | null;
    "error"?: APIError | null;
}

export interface ACPSessionLifecycle {
    "sessionId": string;
    "status": string;
    "lifecyclePolicy": string;
    "loaded": boolean;
    "activeRunId"?: string;
    "pendingInteractions": number;
    "sessionOperations": number;
    "lastActiveAt": string;
    "idleCloseAfterMs": number;
    "idleManagedIdle": boolean;
    "idleManagedEligible": boolean;
    "closedAt"?: string | null;
    "closedReason"?: string;
    "autoCloseAttemptedAt"?: string | null;
    "autoCloseError"?: string;
}

export interface ACPSettingsMutationResult {
    "completed": boolean;
    "persisted": boolean;
    "applied": boolean;
    "restartRequired": boolean;
    "runtimeImpact": string;
    "snapshot"?: ACPManagerSnapshot | null;
    "error"?: APIError | null;
}

export interface ACPStatusResult {
    "enabled": boolean;
    "defaultProfile"?: string;
    "profiles": ACPProfileStatus[] | null;
    "memory": ACPMemoryStatus;
    "error"?: APIError | null;
}

export interface APIError {
    "code": string;
    "message": string;
    "category": ErrorCategory;
    "retryable": boolean;
    "details"?: { [_ in string]?: string } | null;
}

export enum AccessLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AccessRead = "read",
    AccessMutating = "mutating",
    AccessPrivileged = "privileged",
};

export enum Availability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AvailabilityAvailable = "available",
    AvailabilityExperimental = "experimental",
    AvailabilityUnavailable = "unavailable",
};

export interface BasicSettings {
    "port": number;
    "logLevel": string;
    "coreAutostart": boolean;
}

export interface BasicSettingsResult {
    "settings": BasicSettings;
    "coreAutostartMutable": boolean;
    "portMutable": boolean;
    "portDisabledReason"?: string;
    "error"?: APIError | null;
}

export interface BasicSettingsSaveResult {
    "completed": boolean;
    "error"?: APIError | null;
}

export interface ConnectionActionResult {
    "completed": boolean;
    "operationId": string;
    "phase": string;
    "tunnelGeneration"?: string;
    "configRevision"?: string;
    "portObservation"?: desktopruntime$0.PortObservation | null;
    "error"?: APIError | null;
}

export interface ConnectionAutostartRequest {
    "enabled": boolean;
    "configRevision": string;
}

export interface ConnectionPortRequest {
    "candidatePort": number;
    "configRevision": string;
}

export interface ConnectionPreflightResult {
    "observation": desktopruntime$0.PortObservation;
    "error"?: APIError | null;
}

export interface ConnectionSnapshot {
    "portObservation": desktopruntime$0.PortObservation;
    "coreRunning": boolean | null;
    "coreHealth": string;
    "tunnel": desktopruntime$0.TunnelObservation;
    "operations": OperationCapability[] | null;
    "localMCPURL"?: string;
    "publicMCPURL"?: string;
    "port": number;
    "mode": string;
    "oauthEnabled": boolean;
    "oauthPasswordState": desktopruntime$0.OAuthPasswordState;
    "configRevision": string;
    "tunnelGeneration"?: string;
}

export interface ConnectionSnapshotResult {
    "snapshot": ConnectionSnapshot;
    "error"?: APIError | null;
}

export interface ConnectionStatus {
    "mode": string;
    "running": boolean;
    "ready": boolean;
    "startupEnabled": boolean;
    "publicURL"?: string;
}

export interface ConnectionStatusResult {
    "status": ConnectionStatus;
    "error"?: APIError | null;
}

export interface ConnectionTunnelRequest {
    "mode": string;
    "namedOrigin": string;
    "newToken"?: string;
    "configRevision": string;
}

export interface DiagnosticsResult {
    "snapshot": DiagnosticsSnapshot;
    "error"?: APIError | null;
}

export interface DiagnosticsSnapshot {
    "platform": string;
    "architecture": string;
    "runtimeRoot": string;
    "runtimeDirectoryAvailable": boolean;
    "manifestAvailable": boolean;
}

export enum Domain {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DomainRuntime = "runtime",
    DomainSettings = "settings",
    DomainConnection = "connection",
    DomainACP = "acp",
    DomainBrowser = "browser",
    DomainActivity = "activity",
    DomainPermission = "permission",
    DomainMCP = "mcp",
    DomainPlugin = "plugin",
    DomainUpdate = "update",
    DomainDiagnostics = "diagnostics",
};

export interface DomainCapability {
    "domain": Domain;
    "version": number;
    "availability": Availability;
    "operations": OperationCapability[] | null;
    "streams": StreamCapability[] | null;
    "reason"?: string;
}

export enum ErrorCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorCategoryValidation = "validation",
    ErrorCategoryNotFound = "not_found",
    ErrorCategoryConflict = "conflict",
    ErrorCategoryAuthentication = "authentication",
    ErrorCategoryPermission = "permission",
    ErrorCategoryCapacity = "capacity",
    ErrorCategoryUnavailable = "unavailable",
    ErrorCategoryOperation = "operation",
    ErrorCategoryTimeout = "timeout",
    ErrorCategoryCompatibility = "compatibility",
    ErrorCategoryInternal = "internal",
};

export interface MCPActionResult {
    "requestId"?: string;
    "outcome"?: string;
    "outcomeUnknown": boolean;
    "runtimeImpact"?: string;
    "reconnectRequired": boolean;
    "completed": boolean;
    "error"?: APIError | null;
}

export interface MCPAuthCallback {
    "id": string;
    "label": string;
}

export interface MCPAuthorizationResult {
    "requestId"?: string;
    "outcome"?: string;
    "outcomeUnknown": boolean;
    "runtimeImpact"?: string;
    "reconnectRequired": boolean;
    "flowId"?: string;
    "callbackId"?: string;
    "expiresAt"?: string;
    "callbackOptions": MCPAuthCallback[] | null;
    "error"?: APIError | null;
}

export interface MCPAuthorizationStatus {
    "flowId"?: string;
    "status": string;
    "expiresAt"?: string;
    "errorCode"?: string;
    "callbackOptions": MCPAuthCallback[] | null;
}

export interface MCPAuthorizationStatusResult {
    "authorization": MCPAuthorizationStatus;
    "error"?: APIError | null;
}

export interface MCPConfigInput {
    "name"?: string;
    "description"?: string;
    "transport"?: string;
    "protocolVersion"?: string;
    "url"?: string;
    "command"?: string;
    "args"?: string[] | null;
    "cwd"?: string;
    "headerEnv"?: { [_ in string]?: string } | null;
    "envFromEnv"?: { [_ in string]?: string } | null;
    "timeoutMs"?: number | null;
}

export interface MCPEnvironmentEntry {
    "key": string;
    "configured": boolean;
}

export interface MCPEnvironmentResult {
    "requestId"?: string;
    "outcome"?: string;
    "outcomeUnknown": boolean;
    "runtimeImpact"?: string;
    "reconnectRequired": boolean;
    "revision"?: string;
    "items": MCPEnvironmentEntry[] | null;
    "error"?: APIError | null;
}

export interface MCPManagedServer {
    "name": string;
    "displayName": string;
    "description": string;
    "sourceType": string;
    "pluginName"?: string;
    "transport": string;
    "protocolVersion"?: string;
    "url"?: string;
    "urlProtected": boolean;
    "command"?: string;
    "cwd"?: string;
    "args"?: string[] | null;
    "argsProtected": boolean;
    "enabled": boolean;
    "timeoutMs": number;
    "headerEnv"?: { [_ in string]?: string } | null;
    "envFromEnv"?: { [_ in string]?: string } | null;
    "generation": string;
    "environmentConfigured": boolean;
    "enableRequiresEnvironmentConfirmation": boolean;
    "blockedReasons"?: string[] | null;
    "observation": MCPObservation;
}

export interface MCPMutationResult {
    "requestId"?: string;
    "outcome"?: string;
    "outcomeUnknown": boolean;
    "runtimeImpact"?: string;
    "reconnectRequired": boolean;
    "completed": boolean;
    "persisted": boolean;
    "runtimeApplied": boolean;
    "recoveryRequired": boolean;
    "registryRevision"?: string;
    "server"?: MCPManagedServer | null;
    "error"?: APIError | null;
}

export interface MCPObservation {
    "connection": string;
    "status": string;
    "authStatus": string;
    "toolCount"?: number | null;
    "observedAt"?: string;
    "lastErrorCode"?: string;
    "stale": boolean;
}

export interface MCPOperationStatusResult {
    "requestId": string;
    "found": boolean;
    "pending": boolean;
    "outcome": string;
    "outcomeUnknown": boolean;
    "operationAction"?: string;
    "startedAt"?: string;
    "completedAt"?: string;
    "error"?: APIError | null;
}

export interface MCPReconnectResult {
    "requestId"?: string;
    "outcome"?: string;
    "outcomeUnknown": boolean;
    "runtimeImpact"?: string;
    "reconnectRequired": boolean;
    "server"?: MCPManagedServer | null;
    "tools": MCPToolSummary[] | null;
    "toolCount": number;
    "error"?: APIError | null;
}

export interface MCPServerResult {
    "registryRevision"?: string;
    "server"?: MCPManagedServer | null;
    "tools": MCPToolSummary[] | null;
    "toolCount": number;
    "error"?: APIError | null;
}

export interface MCPSnapshot {
    "registryRevision": string;
    "authoritative": boolean;
    "servers": MCPManagedServer[] | null;
}

export interface MCPSnapshotResult {
    "snapshot": MCPSnapshot;
    "error"?: APIError | null;
}

export interface MCPToolSummary {
    "name": string;
    "qualifiedName": string;
    "server": string;
    "sourceType": string;
    "pluginName"?: string;
}

export interface Manifest {
    "protocolVersion": number;
    "minClientVersion": number;
    "maxClientVersion": number;
    "capabilities": DomainCapability[] | null;
}

export interface NegotiationRequest {
    "clientVersion": number;
    "domains"?: Domain[] | null;
}

export interface NegotiationResult {
    "accepted": boolean;
    "serverVersion": number;
    "capabilities": DomainCapability[] | null;
    "error"?: APIError | null;
}

/**
 * This type deliberately cannot be embedded in the ordinary snapshot.
 */
export interface OAuthPasswordRevealResult {
    "password"?: string;
    "state": desktopruntime$0.OAuthPasswordState;
    "configRevision"?: string;
    "tunnelGeneration"?: string;
    "error"?: APIError | null;
}

export interface OperationCapability {
    "name": string;
    "access": AccessLevel;
    "requiresConfirmation": boolean;
    "availability"?: Availability;
    "disabledReason"?: string;
    "nativeRequired"?: boolean;
}

/**
 * PermissionResult projects Core state only; approving never runs the original
 * operation. The caller must retry it through normal Core admission.
 */
export interface PermissionResult {
    "ok": boolean;
    "schema_version": number;
    "state_revision"?: number;
    "runtime_epoch"?: string;
    "policy"?: permission$0.Policy | null;
    "approval"?: permission$0.ApprovalRecord | null;
    "approvals"?: permission$0.ApprovalRecord[] | null;
    "count"?: number;
    "confirmation"?: permission$0.ConfirmationChallenge | null;
    "error"?: APIError | null;
}

export interface PublicEndpointResult {
    "state": string;
    "reasonCode"?: string;
    "configRevision"?: string;
    "tunnelGeneration"?: string;
    "checkedAt": string;
    "error"?: APIError | null;
}

export enum RuntimeAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeActionStart = "start",
    RuntimeActionStop = "stop",
    RuntimeActionRestart = "restart",
};

export interface RuntimeActionResult {
    "action": RuntimeAction;
    "completed": boolean;
    "error"?: APIError | null;
}

export interface RuntimeStatus {
    "running": boolean;
    "healthy": boolean;
    "startupEnabled": boolean;
    "nexusConnected": boolean;
}

export interface RuntimeStatusResult {
    "runtimeRoot": string;
    "status": RuntimeStatus;
    "error"?: APIError | null;
}

export interface StreamCapability {
    "name": string;
    "version": number;
    "transport": string;
    "backpressure": string;
    "maxPayloadBytes"?: number;
}

export interface UpdateCheckResult {
    "status": UpdateStatus;
    "error"?: APIError | null;
}

export interface UpdateStatus {
    "currentVersion": string;
    "latestVersion": string;
    "desktopCurrentVersion"?: string;
    "updateAvailable": boolean;
    "desktopUpdateAvailable": boolean;
}
