// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";

export interface ACPBrokerResources {
    "sessionId": string;
    "browser": ACPBrowserResources;
    "computer": ACPComputerResources;
}

export interface ACPBrowserResources {
    "leaseIds": string[] | null;
    "activeLeases": number;
    "cleanupIssues": number;
}

export interface ACPComputerResources {
    "sessionIds": string[] | null;
    "observeSessions": number;
    "actSessions": number;
}

export interface ACPLifecycleCounts {
    "managed": number;
    "loaded": number;
    "running": number;
    "ready": number;
    "idleManagedIdle": number;
    "idleManagedEligible": number;
    "closed": number;
    "autoCloseFailures": number;
}

export interface ACPLifecycleUpdate {
    "profileId": string;
    "sessionId": string;
    "policy": string;
    "idleCloseAfterMs"?: number;
}

export interface ACPMemoryStatus {
    "endpoint": string;
    "healthy": boolean;
    "version"?: string;
    "backend"?: string;
    "storagePath"?: string;
    "provider"?: string;
    "totalMemories"?: number;
    "protocolVersion": string;
    "error"?: APIError | null;
}

export interface ACPMutationResult {
    "completed": boolean;
    "error"?: APIError | null;
}

export interface ACPProcessStatus {
    "rootPid": number;
    "alive": boolean | null;
    "state": string;
    "descendantCount": number | null;
    "rssBytes": number | null;
    "treeRssBytes": number | null;
    "observedAt": string;
    "error"?: string;
}

export interface ACPProfileInfo {
    "id": string;
    "displayName"?: string;
    "kind": string;
    "source": string;
    "command"?: string;
    "enabled": boolean;
    "installed"?: boolean | null;
    "packageName"?: string;
    "latestVersion"?: string;
    "versionState": string;
}

export interface ACPProfileStatus {
    "profile": ACPProfileInfo;
    "observedAt"?: string;
    "counts": ACPLifecycleCounts;
    "sessions": ACPSessionLifecycle[] | null;
    "adapterProcess"?: ACPProcessStatus | null;
    "resources": ACPBrokerResources[] | null;
    "error"?: APIError | null;
}

export interface ACPSessionLifecycle {
    "sessionId": string;
    "status": string;
    "lifecyclePolicy": string;
    "loaded": boolean;
    "activeRunId"?: string;
    "pendingInteractions": number;
    "sessionOperations": number;
    "lastActiveAt": string;
    "idleCloseAfterMs": number;
    "idleManagedIdle": boolean;
    "idleManagedEligible": boolean;
    "closedAt"?: string | null;
    "closedReason"?: string;
    "autoCloseAttemptedAt"?: string | null;
    "autoCloseError"?: string;
}

export interface ACPStatusResult {
    "enabled": boolean;
    "defaultProfile"?: string;
    "profiles": ACPProfileStatus[] | null;
    "memory": ACPMemoryStatus;
    "error"?: APIError | null;
}

export interface APIError {
    "code": string;
    "message": string;
    "category": ErrorCategory;
    "retryable": boolean;
    "details"?: { [_ in string]?: string } | null;
}

export enum AccessLevel {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AccessRead = "read",
    AccessMutating = "mutating",
    AccessPrivileged = "privileged",
};

export enum Availability {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AvailabilityAvailable = "available",
    AvailabilityExperimental = "experimental",
    AvailabilityUnavailable = "unavailable",
};

export interface BasicSettings {
    "port": number;
    "logLevel": string;
    "coreAutostart": boolean;
}

export interface BasicSettingsResult {
    "settings": BasicSettings;
    "coreAutostartMutable": boolean;
    "error"?: APIError | null;
}

export interface BasicSettingsSaveResult {
    "completed": boolean;
    "error"?: APIError | null;
}

export interface ConnectionActionResult {
    "completed": boolean;
    "error"?: APIError | null;
}

export interface ConnectionStatus {
    "mode": string;
    "running": boolean;
    "ready": boolean;
    "startupEnabled": boolean;
    "publicURL"?: string;
}

export interface ConnectionStatusResult {
    "status": ConnectionStatus;
    "error"?: APIError | null;
}

export interface DiagnosticsResult {
    "snapshot": DiagnosticsSnapshot;
    "error"?: APIError | null;
}

export interface DiagnosticsSnapshot {
    "platform": string;
    "architecture": string;
    "runtimeRoot": string;
    "runtimeDirectoryAvailable": boolean;
    "manifestAvailable": boolean;
}

export enum Domain {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DomainRuntime = "runtime",
    DomainSettings = "settings",
    DomainConnection = "connection",
    DomainACP = "acp",
    DomainBrowser = "browser",
    DomainActivity = "activity",
    DomainPermission = "permission",
    DomainMCP = "mcp",
    DomainPlugin = "plugin",
    DomainUpdate = "update",
    DomainDiagnostics = "diagnostics",
};

export interface DomainCapability {
    "domain": Domain;
    "version": number;
    "availability": Availability;
    "operations": OperationCapability[] | null;
    "streams": StreamCapability[] | null;
    "reason"?: string;
}

export enum ErrorCategory {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ErrorCategoryValidation = "validation",
    ErrorCategoryNotFound = "not_found",
    ErrorCategoryConflict = "conflict",
    ErrorCategoryAuthentication = "authentication",
    ErrorCategoryPermission = "permission",
    ErrorCategoryCapacity = "capacity",
    ErrorCategoryUnavailable = "unavailable",
    ErrorCategoryOperation = "operation",
    ErrorCategoryTimeout = "timeout",
    ErrorCategoryCompatibility = "compatibility",
    ErrorCategoryInternal = "internal",
};

export interface Manifest {
    "protocolVersion": number;
    "minClientVersion": number;
    "maxClientVersion": number;
    "capabilities": DomainCapability[] | null;
}

export interface NegotiationRequest {
    "clientVersion": number;
    "domains"?: Domain[] | null;
}

export interface NegotiationResult {
    "accepted": boolean;
    "serverVersion": number;
    "capabilities": DomainCapability[] | null;
    "error"?: APIError | null;
}

export interface OperationCapability {
    "name": string;
    "access": AccessLevel;
    "requiresConfirmation": boolean;
}

/**
 * PermissionResult projects Core state only; approving never runs the original
 * operation. The caller must retry it through normal Core admission.
 */
export interface PermissionResult {
    "ok": boolean;
    "schema_version": number;
    "state_revision"?: number;
    "runtime_epoch"?: string;
    "policy"?: permission$0.Policy | null;
    "approval"?: permission$0.ApprovalRecord | null;
    "approvals"?: permission$0.ApprovalRecord[] | null;
    "count"?: number;
    "confirmation"?: permission$0.ConfirmationChallenge | null;
    "error"?: APIError | null;
}

export enum RuntimeAction {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RuntimeActionStart = "start",
    RuntimeActionStop = "stop",
    RuntimeActionRestart = "restart",
};

export interface RuntimeActionResult {
    "action": RuntimeAction;
    "completed": boolean;
    "error"?: APIError | null;
}

export interface RuntimeStatus {
    "running": boolean;
    "healthy": boolean;
    "startupEnabled": boolean;
    "nexusConnected": boolean;
}

export interface RuntimeStatusResult {
    "runtimeRoot": string;
    "status": RuntimeStatus;
    "error"?: APIError | null;
}

export interface StreamCapability {
    "name": string;
    "version": number;
    "transport": string;
    "backpressure": string;
    "maxPayloadBytes"?: number;
}

export interface UpdateCheckResult {
    "status": UpdateStatus;
    "error"?: APIError | null;
}

export interface UpdateStatus {
    "currentVersion": string;
    "latestVersion": string;
    "desktopCurrentVersion"?: string;
    "updateAvailable": boolean;
    "desktopUpdateAvailable": boolean;
}
