// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Pair(request: $models.NexusPairRequest): $CancellablePromise<$models.NexusMutationResult> {
    return $Call.ByID(4152135836, request);
}

export function Reconcile(expectedGeneration: string): $CancellablePromise<$models.NexusMutationResult> {
    return $Call.ByID(2081606124, expectedGeneration);
}

export function Snapshot(): $CancellablePromise<$models.NexusSnapshotResult> {
    return $Call.ByID(4124912332);
}
