// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Approval(id: string): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(174789531, id);
}

export function ApproveOnce(confirmationID: string, approvalID: string, version: number, revision: number): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(2603739760, confirmationID, approvalID, version, revision);
}

export function ApproveWorkspace(confirmationID: string, approvalID: string, version: number, revision: number): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(1717517050, confirmationID, approvalID, version, revision);
}

export function BeginConfirmation(mutation: permission$0.ControlMutationRequest): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(426082460, mutation);
}

export function History(status: string, limit: number): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(1505540016, status, limit);
}

export function Reject(confirmationID: string, approvalID: string, version: number, revision: number): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(3649144747, confirmationID, approvalID, version, revision);
}

export function Status(): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(513270218);
}

export function UpdatePolicy(confirmationID: string, revision: number, policy: permission$0.Policy): $CancellablePromise<$models.PermissionResult> {
    return $Call.ByID(2438024963, confirmationID, revision, policy);
}
