// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ChooseCandidate(input: $models.PluginCandidatePickerInput): $CancellablePromise<$models.PluginCandidateResult> {
    return $Call.ByID(2675707194, input);
}

export function DiscardCandidate(candidateID: string): $CancellablePromise<$models.PluginCandidateActionResult> {
    return $Call.ByID(2956432263, candidateID);
}

export function Environment(name: string, component: string): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(457953653, name, component);
}

export function Inspect(name: string): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(873218856, name);
}

export function InstallCandidate(input: $models.PluginCandidateMutationInput): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(2109307472, input);
}

export function OperationStatus(id: string): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(3571573255, id);
}

export function RemoveKeep(input: $models.PluginMutationInput): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(2393233557, input);
}

export function RemovePurge(input: $models.PluginMutationInput): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(1569761715, input);
}

export function SetEnabled(input: $models.PluginMutationInput, enabled: boolean): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(3385552093, input, enabled);
}

export function SetEnvironment(input: $models.PluginEnvironmentInput): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(3550104077, input);
}

export function Snapshot(): $CancellablePromise<$models.PluginSnapshotResult> {
    return $Call.ByID(4100523056);
}

export function UnsetEnvironment(input: $models.PluginEnvironmentInput): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(147762290, input);
}

export function UpdateCandidate(input: $models.PluginCandidateMutationInput): $CancellablePromise<$models.PluginOperationResult> {
    return $Call.ByID(2973316410, input);
}
