// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Action(action: $models.RuntimeAction): $CancellablePromise<$models.RuntimeActionResult> {
    return $Call.ByID(3011621917, action);
}

export function Status(): $CancellablePromise<$models.RuntimeStatusResult> {
    return $Call.ByID(4035493809);
}
