// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum OAuthPasswordState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OAuthPasswordStored = "stored",
    OAuthPasswordMissing = "missing",
    OAuthPasswordUnreadable = "unreadable",
    OAuthPasswordUnavailable = "unavailable",
};

/**
 * PortObservation contains only safe metadata, never OS errors or process paths.
 */
export interface PortObservation {
    "configuredPort": number;
    "observedPort": number;
    "state": PortState;
    "reasonCode": string;
    "observedAt": string;
    "configRevision": string;
}

export enum PortState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PortAvailable = "available",
    PortOwnedByNext = "owned_by_next",
    PortReserved = "reserved",
    PortConflict = "conflict",
    PortUnknown = "unknown",
};

/**
 * Nil observations mean unknown; false is an actual negative observation.
 */
export interface TunnelObservation {
    "registered": boolean | null;
    "running": boolean | null;
    "connected": boolean | null;
    "autostart": string;
    "token_state": string;
    "tunnel_generation": string;
    "public_endpoint": string;
    "remote_route"?: string;
    "recovery_required": boolean;
}
