// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServiceStatus 是桌面端和 CLI 共享的结构化运行状态。
 * 生命周期操作统一返回 JSON，避免桌面端继续解析 PowerShell 文本。
 */
export interface ServiceStatus {
    "running": boolean;
    "healthy": boolean;
    "startup_enabled": boolean;
    "nexus_connected": boolean;
}
