// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ApprovalCategories {
    "file_writes": boolean;
    "commands": boolean;
    "network": boolean;
    "mcp": boolean;
    "management": boolean;
    "other": boolean;
}

export interface ApprovalPolicy {
    "mode": string;
    "granular"?: ApprovalCategories | null;
}

export interface ApprovalRecord {
    "decision"?: Decision | null;
    "can_approve_once": boolean;
    "can_approve_workspace": boolean;
    "workspace_unavailable_reason"?: string;
    "schema_version": number;
    "version": number;
    "approval_id": string;
    "audit": AuditBinding;
    "binding": AuditSafeBinding;
    "tool": string;
    "action"?: string;
    "summary": string;
    "scope": string;
    "reason": string;
    "rule_id"?: string;
    "policy_revision": number;
    "granted_policy_revision"?: number;
    "runtime_epoch": string;
    "status": string;
    "created_at": string;
    "expires_at": string;
    "decided_at"?: string | null;
    "decided_by"?: string;
    "grant_kind": string;
    "granted_rule_id"?: string;
    "retry_call_id"?: string;
    "dispatch_outcome": string;
}

export interface AuditBinding {
    "call_id": string;
    "parent_call_id"?: string;
    "original_approval_id"?: string;
    "original_call_id"?: string;
}

/**
 * AuditSafeBinding omits roots and hashes identity values; it cannot authorize.
 */
export interface AuditSafeBinding {
    "principal_kind": string;
    "principal_hash": string;
    "source": string;
    "workspace_hash"?: string;
    "session_hash"?: string;
    "provider_hash"?: string;
}

/**
 * ConfirmationChallenge is safe bounded metadata for the native Desktop
 * client. The credential and request fingerprint never appear here.
 */
export interface ConfirmationChallenge {
    "schema_version": number;
    "confirmation_id": string;
    "kind": string;
    "approval_id"?: string;
    "approval_version"?: number;
    "policy_revision": number;
    "expires_at": string;
}

/**
 * ControlMutationRequest is the normalized authorization subject for a
 * permission mutation. Actor is deliberately absent; Core supplies it after
 * control authorization succeeds.
 */
export interface ControlMutationRequest {
    "kind": string;
    "approval_id"?: string;
    "approval_version"?: number;
    "policy_revision": number;
    "policy"?: Policy | null;
}

export interface Decision {
    "effect": string;
    "rule_id": string;
    "reason": string;
    "policy_revision": number;
    "binding": AuditSafeBinding;
    "effective": Effective;
    "sources": DecisionSource[] | null;
}

export interface DecisionSource {
    "kind": string;
    "id"?: string;
    "effect": string;
    "reason": string;
}

export interface Effective {
    "mode": string;
    "settings": Settings;
    "workspace_id"?: string;
}

export interface Policy {
    "schema_version": number;
    "revision": number;
    "global_mode": string;
    "settings": Settings;
    "scopes": WorkspaceScope[] | null;
    "rules": Rule[] | null;
}

export interface Profile {
    "filesystem": string;
    "network": string;
    "sandbox_boundary": string;
}

/**
 * Rules match exact tool names; an empty action matches every action of that
 * tool. Empty WorkspaceID means global. There are no implicit glob patterns.
 */
export interface Rule {
    "id": string;
    "tool": string;
    "action"?: string;
    "workspace_id"?: string;
    "effect": string;
    "reason": string;
}

export interface Settings {
    "permission_profile": Profile;
    "approval_policy": ApprovalPolicy;
    "approval_reviewer": string;
}

export interface WorkspaceScope {
    "workspace_id": string;
    "mode"?: string;
    "settings"?: Settings | null;
}
